variables:
  - &cachix-use |
    set -e
    nix --extra-experimental-features 'nix-command flakes' profile install nixpkgs#cachix
    cachix use tiborpilz
    cachix use nix-community

  - &nix-step
      image: nixos/nix
      environment:
        CACHIX_AUTH_TOKEN:
          from_secret: cachix_auth_token

when:
  - event: push
    branch: main
  - event: pull_request
  - event: manual

steps:
  build-doom-emacs-standalone:
    <<: *nix-step
    commands:
      - *cachix-use
      - |
        set -e
        if [ "$CI_PIPELINE_EVENT" = "push" ] || [ "$CI_PIPELINE_EVENT" = "manual" ]; then
          cachix authtoken "$CACHIX_AUTH_TOKEN"
          cachix watch-exec tiborpilz -- nix --extra-experimental-features 'nix-command flakes' build .#doom-emacs-standalone
        else
          echo "Event $CI_PIPELINE_EVENT: building without cachix push."
          nix --extra-experimental-features 'nix-command flakes' build .#doom-emacs-standalone
        fi
