version: "3"
tasks:
  build-nixos-edge:
    cmds:
      - "nix build .#nixosConfigurations.edge.config.system.build.toplevel"
  build-nixos-homeserver:
    cmds:
      - "nix build .#nixosConfigurations.homeserver.config.system.build.toplevel"
  build-nixos-ideapad:
    cmds:
      - "nix build .#nixosConfigurations.ideapad.config.system.build.toplevel"
  build-nixos-thinkyMcThinkpad:
    cmds:
      - "nix build .#nixosConfigurations.thinkyMcThinkpad.config.system.build.toplevel"
  "build-package-@volar/vue-language-server":
    cmds:
      - "nix build .#@volar/vue-language-server"
  build-package-copilot:
    cmds:
      - "nix build .#copilot"
  build-package-flakeRepl:
    cmds:
      - "nix build .#flakeRepl"
  build-package-generateTaskfile:
    cmds:
      - "nix build .#generateTaskfile"
  build-package-taskgen:
    cmds:
      - "nix build .#taskgen"
