# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/parser-7.23.0" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.23.0.tgz";
        sha512 = "vvPKKdMemU85V9WE/l5wZEmImpCtLqbnTvqDS2U1fJ96KrxoW7KrXhNsNCblQlg8Ck4b85yxdTyelsMUgFUXiw==";
      };
    };
    "@emmetio/abbreviation-2.3.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz";
        sha512 = "mgv58UrU3rh4YgbE/TzgLQwJ3pFsHHhCLqY20aJq+9comytTXUDNGG/SMtSeMJdkpxgXSXunBGLD8Boka3JyVA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.8" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz";
        sha512 = "s9yjhJ6saOO/uk1V74eifykk2CBYi01STTK3WlXWGOepyKa23ymJ053+DNQjpFcy1ingpaO7AxCcwLvHFY9tuw==";
      };
    };
    "@emmetio/scanner-1.0.4" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz";
        sha512 = "IqRuJtQff7YHHBk4G8YZ45uB9BaAGcwQeVzgj/zj8/UdOhtQpEIupUhSk8dys6spFIWVZVeK20CzGEnqR5SbqA==";
      };
    };
    "@johnsoncodehk/pug-beautify-0.2.2" = {
      name = "_at_johnsoncodehk_slash_pug-beautify";
      packageName = "@johnsoncodehk/pug-beautify";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@johnsoncodehk/pug-beautify/-/pug-beautify-0.2.2.tgz";
        sha512 = "qqNS/YD0Nck5wtQLCPHAfGVgWbbGafxSPjNh0ekYPFSNNqnDH2kamnduzYly8IiADmeVx/MfAE1njMEjVeHTMA==";
      };
    };
    "@types/node-17.0.45" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "17.0.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-17.0.45.tgz";
        sha512 = "w+tIMs3rq2afQdsPJlODhoUEKzFP1ayaoyl1CcnwtIlsVe7K7bA1NGm4s3PraqTLlXnbIN84zuBlxBWo1u9BLw==";
      };
    };
    "@volar/language-core-1.10.1" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-1.10.1.tgz";
        sha512 = "JnsM1mIPdfGPxmoOcK1c7HYAsL6YOv0TCJ4aW3AXPZN/Jb4R77epDyMZIVudSGjWMbvv/JfUa+rQ+dGKTmgwBA==";
      };
    };
    "@volar/language-server-1.10.1" = {
      name = "_at_volar_slash_language-server";
      packageName = "@volar/language-server";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-server/-/language-server-1.10.1.tgz";
        sha512 = "UXgRMAPKoy4EZBcBT1SFp8YIb5AJqe7Is1/TnqRUq0LBBV2M7HpEeHHI8E4fy05Eg4TlSVRcrlZtiTrY9fRjJg==";
      };
    };
    "@volar/language-service-1.10.1" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-1.10.1.tgz";
        sha512 = "9AfMd8DeBuiw5twyXCL4Dw/9dg7djs2GAMQ5YY6LlN4v6u5IwU+foM/un5F7yzE94v2cuI+NN9LtHeR87AXpRA==";
      };
    };
    "@volar/source-map-1.10.1" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-1.10.1.tgz";
        sha512 = "3/S6KQbqa7pGC8CxPrg69qHLpOvkiPHGJtWPkI/1AXCsktkJ6gIk/5z4hyuMp8Anvs6eS/Kvp/GZa3ut3votKA==";
      };
    };
    "@volar/typescript-1.10.1" = {
      name = "_at_volar_slash_typescript";
      packageName = "@volar/typescript";
      version = "1.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript/-/typescript-1.10.1.tgz";
        sha512 = "+iiO9yUSRHIYjlteT+QcdRq8b44qH19/eiUZtjNtuh6D9ailYM7DVR0zO2sEgJlvCaunw/CF9Ov2KooQBpR4VQ==";
      };
    };
    "@vscode/emmet-helper-2.9.2" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.9.2.tgz";
        sha512 = "MaGuyW+fa13q3aYsluKqclmh62Hgp0BpKIqS66fCxfOaBcVQ1OnMQxRRgQUYnCkxFISAQlkJ0qWWPyXjro1Qrg==";
      };
    };
    "@vscode/l10n-0.0.11" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.11.tgz";
        sha512 = "ukOMWnCg1tCvT7WnDfsUKQOFDQGsyR5tNgRpwmqi+5/vzU3ghdDXzvIM4IOPdSb3OeSsBNvmSL8nxIVOqi2WXA==";
      };
    };
    "@vscode/l10n-0.0.16" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.16.tgz";
        sha512 = "JT5CvrIYYCrmB+dCana8sUqJEcGB1ZDXNLMQ2+42bW995WmNoenijWMUdZfwmuQUTQcEVVIa2OecZzTYWUW9Cg==";
      };
    };
    "@vue/compiler-core-3.3.4" = {
      name = "_at_vue_slash_compiler-core";
      packageName = "@vue/compiler-core";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-core/-/compiler-core-3.3.4.tgz";
        sha512 = "cquyDNvZ6jTbf/+x+AgM2Arrp6G4Dzbb0R64jiG804HRMfRiFXWI6kqUVqZ6ZR0bQhIoQjB4+2bhNtVwndW15g==";
      };
    };
    "@vue/compiler-dom-3.3.4" = {
      name = "_at_vue_slash_compiler-dom";
      packageName = "@vue/compiler-dom";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/compiler-dom/-/compiler-dom-3.3.4.tgz";
        sha512 = "wyM+OjOVpuUukIq6p5+nwHYtj9cFroz9cwkfmP9O1nzH68BenTTv0u7/ndggT8cIQlnBeOo6sUT/gvHcIkLA5w==";
      };
    };
    "@vue/language-core-1.8.15" = {
      name = "_at_vue_slash_language-core";
      packageName = "@vue/language-core";
      version = "1.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-core/-/language-core-1.8.15.tgz";
        sha512 = "zche5Aw8kkvp3YaghuLiOZyVIpoWHjSQ0EfjxGSsqHOPMamdCoa9x3HtbenpR38UMUoKJ88wiWuiOrV3B/Yq+A==";
      };
    };
    "@vue/language-service-1.8.15" = {
      name = "_at_vue_slash_language-service";
      packageName = "@vue/language-service";
      version = "1.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/language-service/-/language-service-1.8.15.tgz";
        sha512 = "n9K7+meGqzN+t4iG3fNcUUNxnhVS1in9egVnFHTdb67NR4MT4vpLBke7EXUKHFkKAGrB0ZkEEPKTr5+qe4AwoQ==";
      };
    };
    "@vue/reactivity-3.3.4" = {
      name = "_at_vue_slash_reactivity";
      packageName = "@vue/reactivity";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/reactivity/-/reactivity-3.3.4.tgz";
        sha512 = "kLTDLwd0B1jG08NBF3R5rqULtv/f8x3rOFByTDz4J53ttIQEDmALqKqXY0J+XQeN0aV2FBxY8nJDf88yvOPAqQ==";
      };
    };
    "@vue/shared-3.3.4" = {
      name = "_at_vue_slash_shared";
      packageName = "@vue/shared";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vue/shared/-/shared-3.3.4.tgz";
        sha512 = "7OjdcV8vQ74eiz1TZLzZP4JwqM5fA94K6yntPS5Z25r9HDuGNzaGdgvwKYq6S+MxwF0TFRwe50fIR/MYnakdkQ==";
      };
    };
    "acorn-7.4.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "7.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-7.4.1.tgz";
        sha512 = "nQyp0o1/mNdbTO1PO6kHkwSrmgZ0MT/jCCpNiwbUjGoRN4dlBhqJtoQuCnEOKzgTVwg0ZWiCoQy6SxMebQVh8A==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-2.0.1" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-2.0.1.tgz";
        sha512 = "XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "character-parser-2.2.0" = {
      name = "character-parser";
      packageName = "character-parser";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-parser/-/character-parser-2.2.0.tgz";
        sha512 = "+UqJQjFEFaTAs3bNsF2j2kEN1baG/zghZbdqoYEDxGZtJo9LBzl1A+m0D4n3qKx8N2FNv8/Xp6yV9mQmBuptaw==";
      };
    };
    "de-indent-1.0.2" = {
      name = "de-indent";
      packageName = "de-indent";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/de-indent/-/de-indent-1.0.2.tgz";
        sha512 = "e/1zu3xH5MQryN2zdVaF0OrdNLUbvWxzMbi+iNA6Bky7l1RoP8a2fIbRocyHclXt/arDrrR6lL3TqFD9pMQTsg==";
      };
    };
    "emmet-2.4.6" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.4.6.tgz";
        sha512 = "dJfbdY/hfeTyf/Ef7Y7ubLYzkBvPQ912wPaeVYpAxvFxkEBf/+hJu4H6vhAvFN6HlxqedlfVn2x1S44FfQ97pg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-intrinsic-1.2.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.1.tgz";
        sha512 = "2DcsyfABl+gVHEfCOaTrWgyt+tb6MSEGmKq+kI5HwLbIYgjgmMcV8KQ41uaKz1xxUcn9tJtgFbQUEVcEbd0FYw==";
      };
    };
    "has-1.0.4" = {
      name = "has";
      packageName = "has";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.4.tgz";
        sha512 = "qdSAmqLF6209RFj4VVItywPMbm3vWylknmB3nvNiUIs72xAimcM8nVYxYr7ncvZq5qzk9MKIZR8ijqD/1QuYjQ==";
      };
    };
    "has-proto-1.0.1" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.1.tgz";
        sha512 = "7qE+iP+O+bgF9clE5+UoBFzE65mlBiVj3tKCrlNQ0Ogwm0BjpT/gK4SlLYDMybDh5I3TCTKnPPa0oMG7JDYrhg==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "is-expression-4.0.0" = {
      name = "is-expression";
      packageName = "is-expression";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-expression/-/is-expression-4.0.0.tgz";
        sha512 = "zMIXX63sxzG3XrkHkrAPvm/OVZVSCPNkwMHU8oTX7/U3AL78I0QXCEICXUM13BIa8TYGZ68PiTKfQz3yaTNr4A==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.2.0" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.2.0.tgz";
        sha512 = "gfFQZrcTc8CnKXp6Y4/CBT3fTc0OVuDofpre4aEeEpSBPV5X5v4+Vmx+8snU7RLPrNHPKSgLxGo9YuQzz20o+w==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "minimatch-9.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "9.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-9.0.3.tgz";
        sha512 = "RHiac9mvaRw0x3AYRgDC1CxAP7HTcNrrECeA8YYJeWnpo+2Q5CegtZjaotWTWxDG3UeGA1coE05iH1mPjT/2mg==";
      };
    };
    "muggle-string-0.3.1" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.3.1.tgz";
        sha512 = "ckmWDJjphvd/FvZawgygcUeQCxzvohjFO5RxTjj4eq8kw359gFF3E1brjfI+viLMxss5JrHTDRHZvu2/tuy0Qg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "pug-error-2.0.0" = {
      name = "pug-error";
      packageName = "pug-error";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-error/-/pug-error-2.0.0.tgz";
        sha512 = "sjiUsi9M4RAGHktC1drQfCr5C5eriu24Lfbt4s+7SykztEOwVZtbFk1RRq0tzLxcMxMYTBR+zMQaG07J/btayQ==";
      };
    };
    "pug-lexer-5.0.1" = {
      name = "pug-lexer";
      packageName = "pug-lexer";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-lexer/-/pug-lexer-5.0.1.tgz";
        sha512 = "0I6C62+keXlZPZkOJeVam9aBLVP2EnbeDw3An+k0/QlqdwH6rv8284nko14Na7c0TtqtogfWXcRoFE4O4Ff20w==";
      };
    };
    "pug-parser-6.0.0" = {
      name = "pug-parser";
      packageName = "pug-parser";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pug-parser/-/pug-parser-6.0.0.tgz";
        sha512 = "ukiYM/9cH6Cml+AOl5kETtM9NR3WulyVP2y4HOU45DyMim1IeP/OOiyEWRr6qk5I5klpsBnbuHpwKmTx6WURnw==";
      };
    };
    "request-light-0.7.0" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz";
        sha512 = "lMbBMrDoxgsyO+yB3sDcrDuX85yYt7sS8BfQd11jtbW/z5ZWgLZRcEGLsLoYw7I0WSUGQBs8CC8ScIxkTX1+6Q==";
      };
    };
    "semver-7.5.4" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.4.tgz";
        sha512 = "1bCSESV6Pv+i21Hvpxp3Dx+pSD8lIPt8uVjRrxAUt/nbswYc+tK6Y2btiULjd4+fnq15PX+nqQDC7Oft7WkwcA==";
      };
    };
    "source-map-js-1.0.2" = {
      name = "source-map-js";
      packageName = "source-map-js";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-js/-/source-map-js-1.0.2.tgz";
        sha512 = "R0XvVJ9WusLiqTCEiGCmICCMplcCkIwwR11mOSD9CR5u+IXYdiseeEuXCVAjS54zqwkLcPNnmU4OeJ6tUrWhDw==";
      };
    };
    "token-stream-1.0.0" = {
      name = "token-stream";
      packageName = "token-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-stream/-/token-stream-1.0.0.tgz";
        sha512 = "VSsyNPPW74RpHwR8Fc21uubwHY7wMDeJLys2IX5zJNih+OnAnaifKHo+1LHT7DAdloQ7apeaaWg8l7qnf/TnEg==";
      };
    };
    "typesafe-path-0.2.2" = {
      name = "typesafe-path";
      packageName = "typesafe-path";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typesafe-path/-/typesafe-path-0.2.2.tgz";
        sha512 = "OJabfkAg1WLZSqJAJ0Z6Sdt3utnbzr/jh+NAHoyWHJe8CMSy79Gm085094M9nvTPy22KzTVn5Zq5mbapCI/hPA==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
    "typescript-5.2.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.2.2.tgz";
        sha512 = "mI4WrpHsbCIcwT9cF4FZvr80QUeKvsUsUvKDoR+X/7XHQH98xYD8YHZg7ANtz2GtZt/CBq2QJ0thkGJMHfqc1w==";
      };
    };
    "typescript-auto-import-cache-0.3.0" = {
      name = "typescript-auto-import-cache";
      packageName = "typescript-auto-import-cache";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.0.tgz";
        sha512 = "Rq6/q4O9iyqUdjvOoyas7x/Qf9nWUMeqpP3YeTaLA+uECgfy5wOhfOS+SW/+fZ/uI/ZcKaf+2/ZhFzXh8xfofQ==";
      };
    };
    "volar-service-css-0.0.13" = {
      name = "volar-service-css";
      packageName = "volar-service-css";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-css/-/volar-service-css-0.0.13.tgz";
        sha512 = "WAuo7oDYgTQ1cr45EqTGoPGtClj0f5PZDQARgQveXKu0CQgyXn8Bs7c4EjDR0fNLhiG3moBEs2uSUGxjSKghxw==";
      };
    };
    "volar-service-emmet-0.0.13" = {
      name = "volar-service-emmet";
      packageName = "volar-service-emmet";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-emmet/-/volar-service-emmet-0.0.13.tgz";
        sha512 = "y/U3up9b3YA8DL36h6KUGnBoH/TUmr1Iv9HWuSeWJKoA6LOt57AOIgzl7+/zY8d+0+C0jGqpV4CM8V5+TjptvQ==";
      };
    };
    "volar-service-html-0.0.13" = {
      name = "volar-service-html";
      packageName = "volar-service-html";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-html/-/volar-service-html-0.0.13.tgz";
        sha512 = "Y4pfmNsIpkDTixJVdobRMDZm5Ax90magUCdYl6HUN0/RstxHb3ogEodTT1GtNmoek/YYTrxbWZYN/Yq49+9zdg==";
      };
    };
    "volar-service-json-0.0.13" = {
      name = "volar-service-json";
      packageName = "volar-service-json";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-json/-/volar-service-json-0.0.13.tgz";
        sha512 = "1JVy/3jRY3bmZDaoLE0jk+rLrabYkUoNHodc0ir9T2VBIV4TK3jU9lee57HS9aoQoY0evI/XBdCqZHgxwz236A==";
      };
    };
    "volar-service-pug-0.0.13" = {
      name = "volar-service-pug";
      packageName = "volar-service-pug";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug/-/volar-service-pug-0.0.13.tgz";
        sha512 = "BAfyYtXZj+HTys0nTs81ivByGNdi7nAcSgWPDtKqy4H1Ts5gvfg0/hbLhv5KLJxsTONC3Ejw4vXDgCgQA/Vhiw==";
      };
    };
    "volar-service-pug-beautify-0.0.13" = {
      name = "volar-service-pug-beautify";
      packageName = "volar-service-pug-beautify";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-pug-beautify/-/volar-service-pug-beautify-0.0.13.tgz";
        sha512 = "86W2FrgHhfX8LyF0wzhjTXOKz352FHfkofm6r6ZRw2rTM4RJ4RSHfnFjtK+jTcg59uM+8xAl9Tcb15APivXosg==";
      };
    };
    "volar-service-typescript-0.0.13" = {
      name = "volar-service-typescript";
      packageName = "volar-service-typescript";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.13.tgz";
        sha512 = "fwpoA1L/bCXz5hl9W4EYJYNyorocfdfbLQ9lTM3rPVOzjRZVknEE8XP31RMPZhEg3sOxKh18+sLEL7j3bip8ew==";
      };
    };
    "volar-service-typescript-twoslash-queries-0.0.13" = {
      name = "volar-service-typescript-twoslash-queries";
      packageName = "volar-service-typescript-twoslash-queries";
      version = "0.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript-twoslash-queries/-/volar-service-typescript-twoslash-queries-0.0.13.tgz";
        sha512 = "KGk5ek2v7T8OSY9YdMmqGOT0KkoUQAe8RbPmoZibT9F3vgmmWVgaAoIlDZ1vwt7VfQeZvRmhvRJhqpCA80ZF8Q==";
      };
    };
    "vscode-css-languageservice-6.2.9" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.2.9.tgz";
        sha512 = "9MsOvAi+VycKomQ7KEq4o/hLtjHHrtRLLl8lM9nMcH8cxfNI7/6jVXmsV/7pdbDWu9L3DZhsspN1eMXZwiOymw==";
      };
    };
    "vscode-html-languageservice-5.1.0" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.1.0.tgz";
        sha512 = "cGOu5+lrz+2dDXSGS15y24lDtPaML1T8K/SfqgFbLmCZ1btYOxceFieR+ybTS2es/A67kRc62m2cKFLUQPWG5g==";
      };
    };
    "vscode-json-languageservice-5.3.6" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.3.6.tgz";
        sha512 = "P4kthBi3GMLKi7Lmp24nkKHAWxbFfCsIDBPlMrK1Tag1aqbl3l60UferDkfAasupDVBM2dekbArzGycUjw8OHA==";
      };
    };
    "vscode-jsonrpc-6.0.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-6.0.0.tgz";
        sha512 = "wnJA4BnEjOSyFMvjZdpiOwhSq9uDoK8e/kpRJDTaMYzwlkrhG1fwDIZI94CLsLzlCK5cIbMMtFlJlfR57Lavmg==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-languageserver-7.0.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-7.0.0.tgz";
        sha512 = "60HTx5ID+fLRcgdHfmz0LDZAXYEV68fzwG0JWwEPBode9NuMYTIxuYXPg4ngO8i8+Ou0lM7y6GzaYWbiDL0drw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.16.0" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.16.0.tgz";
        sha512 = "sdeUoAawceQdgIfTI+sdcwkiK2KU+2cbEYA0agzM2uqaUy2UpnnGHtWTHVEtS0ES4zHU0eMFRGN+oQgDxlD66A==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-textdocument-1.0.11" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.11.tgz";
        sha512 = "X+8T3GoiwTVlJbicx/sIAF+yuJAqz8VvwJyoMVhwEMoEKE/fkDmrqUgDMyBECcM2A2frVZIUj5HI/ErRXCfOeA==";
      };
    };
    "vscode-languageserver-types-3.16.0" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.16.0.tgz";
        sha512 = "k8luDIWJWyenLc5ToFQQMaSrqCHiLwyKPHKPQZ5zz21vM+vIVUSvsRpcbiECH4WR88K2XZqc4ScRcZ7nk/jbeA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-2.1.2" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-2.1.2.tgz";
        sha512 = "8TEXQxlldWAuIODdukIb+TR5s+9Ds40eSJrw+1iDDA9IFORPjMELarNQE3myz5XIkWWpdprmJjm1/SxMlWOC8A==";
      };
    };
    "vscode-uri-3.0.8" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.0.8.tgz";
        sha512 = "AyFQ0EVmsOZOlAnxoFOGOq1SQDWAB7C6aqMGS23svWAllfOaxbuFvcT8D1i8z3Gyn8fraVeZNNmN6e9bxxXkKw==";
      };
    };
    "vue-component-meta-1.8.15" = {
      name = "vue-component-meta";
      packageName = "vue-component-meta";
      version = "1.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-component-meta/-/vue-component-meta-1.8.15.tgz";
        sha512 = "eQ2fdJ/sQuI/SZhTEEYgEfc7QXl1MLfKbAxkUiTr9IE3TyWmW6JQzzp0EgVEOaGKzSNuw8Zau6uWC8RVsK7mlA==";
      };
    };
    "vue-component-type-helpers-1.8.15" = {
      name = "vue-component-type-helpers";
      packageName = "vue-component-type-helpers";
      version = "1.8.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-component-type-helpers/-/vue-component-type-helpers-1.8.15.tgz";
        sha512 = "RKiPRKW4BdwgmQ9vaNkHYKAThdTbgU4TOphVyyzqxRwsOJOoRIrb+vB49XLvs5CKPNrvxMXZMwPe5FyJCqFWyg==";
      };
    };
    "vue-template-compiler-2.7.14" = {
      name = "vue-template-compiler";
      packageName = "vue-template-compiler";
      version = "2.7.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-template-compiler/-/vue-template-compiler-2.7.14.tgz";
        sha512 = "zyA5Y3ArvVG0NacJDkkzJuPQDF8RFeRlzV2vLeSnhSpieO6LK2OVbdLPi5MPPs09Ii+gMO8nY4S3iKQxBxDmWQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
  };
in
{
  "@vue/language-server" = nodeEnv.buildNodePackage {
    name = "_at_vue_slash_language-server";
    packageName = "@vue/language-server";
    version = "1.8.15";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vue/language-server/-/language-server-1.8.15.tgz";
      sha512 = "5tysnIMy8qfiMxnS7CAyZAWD8cuapt8zaB8iGsLE+Jma1+L61X5qcIxWOUNBA0428QTwNdqEOOzdqoU/prlORw==";
    };
    dependencies = [
      sources."@babel/parser-7.23.0"
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/scanner-1.0.4"
      sources."@johnsoncodehk/pug-beautify-0.2.2"
      sources."@volar/language-core-1.10.1"
      sources."@volar/language-server-1.10.1"
      sources."@volar/language-service-1.10.1"
      sources."@volar/source-map-1.10.1"
      sources."@volar/typescript-1.10.1"
      (sources."@vscode/emmet-helper-2.9.2" // {
        dependencies = [
          sources."vscode-uri-2.1.2"
        ];
      })
      sources."@vscode/l10n-0.0.11"
      sources."@vue/compiler-core-3.3.4"
      sources."@vue/compiler-dom-3.3.4"
      sources."@vue/language-core-1.8.15"
      sources."@vue/language-service-1.8.15"
      sources."@vue/reactivity-3.3.4"
      sources."@vue/shared-3.3.4"
      sources."acorn-7.4.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-2.0.1"
      sources."call-bind-1.0.2"
      sources."character-parser-2.2.0"
      sources."de-indent-1.0.2"
      sources."emmet-2.4.6"
      sources."estree-walker-2.0.2"
      sources."function-bind-1.1.1"
      sources."get-intrinsic-1.2.1"
      sources."has-1.0.4"
      sources."has-proto-1.0.1"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."he-1.2.0"
      sources."is-expression-4.0.0"
      sources."is-regex-1.1.4"
      sources."jsonc-parser-2.3.1"
      sources."lru-cache-6.0.0"
      sources."minimatch-9.0.3"
      sources."muggle-string-0.3.1"
      sources."object-assign-4.1.1"
      sources."pug-error-2.0.0"
      sources."pug-lexer-5.0.1"
      sources."pug-parser-6.0.0"
      sources."request-light-0.7.0"
      sources."semver-7.5.4"
      sources."source-map-js-1.0.2"
      sources."token-stream-1.0.0"
      sources."typesafe-path-0.2.2"
      sources."typescript-5.2.2"
      sources."typescript-auto-import-cache-0.3.0"
      sources."volar-service-css-0.0.13"
      sources."volar-service-emmet-0.0.13"
      sources."volar-service-html-0.0.13"
      sources."volar-service-json-0.0.13"
      sources."volar-service-pug-0.0.13"
      sources."volar-service-pug-beautify-0.0.13"
      sources."volar-service-typescript-0.0.13"
      sources."volar-service-typescript-twoslash-queries-0.0.13"
      (sources."vscode-css-languageservice-6.2.9" // {
        dependencies = [
          sources."@vscode/l10n-0.0.16"
        ];
      })
      (sources."vscode-html-languageservice-5.1.0" // {
        dependencies = [
          sources."@vscode/l10n-0.0.16"
        ];
      })
      (sources."vscode-json-languageservice-5.3.6" // {
        dependencies = [
          sources."@vscode/l10n-0.0.16"
          sources."jsonc-parser-3.2.0"
        ];
      })
      sources."vscode-jsonrpc-8.1.0"
      (sources."vscode-languageserver-8.1.0" // {
        dependencies = [
          sources."vscode-languageserver-protocol-3.17.3"
        ];
      })
      (sources."vscode-languageserver-protocol-3.17.5" // {
        dependencies = [
          sources."vscode-jsonrpc-8.2.0"
          sources."vscode-languageserver-types-3.17.5"
        ];
      })
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.17.3"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.0.8"
      sources."vue-component-meta-1.8.15"
      sources."vue-component-type-helpers-1.8.15"
      sources."vue-template-compiler-2.7.14"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://github.com/vuejs/language-tools#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  emmet-ls = nodeEnv.buildNodePackage {
    name = "emmet-ls";
    packageName = "emmet-ls";
    version = "0.4.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/emmet-ls/-/emmet-ls-0.4.2.tgz";
      sha512 = "nwiUsbph9c4TkZjrKb7OqrUG6XQ3AxmmVn3IDR6FTx/xLLAegpmSxfOrvvPADbz9vOkSP6jjShpux1tNrqqIkQ==";
    };
    dependencies = [
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/scanner-1.0.4"
      sources."@types/node-17.0.45"
      sources."emmet-2.4.6"
      sources."typescript-4.9.5"
      sources."vscode-jsonrpc-6.0.0"
      sources."vscode-languageserver-7.0.0"
      sources."vscode-languageserver-protocol-3.16.0"
      sources."vscode-languageserver-textdocument-1.0.11"
      sources."vscode-languageserver-types-3.16.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "emmet support by LSP";
      homepage = "https://github.com/aca/emmet-ls#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@previewjs/cli" = nodeEnv.buildNodePackage {
    name = "_at_previewjs_slash_cli";
    packageName = "@previewjs/cli";
    version = "1.25.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/@previewjs/cli/-/cli-1.25.3.tgz";
      sha512 = "LSbwb8qnVNw22i/qkaFsEg8hi6UrQjI9GDmjigdx1VTrjIz4dLq9H4Pd0ZNJi0IIhjK/i5OF8ekZ1FfbAUSQMQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      homepage = "https://previewjs.com";
      license = "https://previewjs.com/eula";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
