# yaml-language-server: $schema=https://devenv.sh/devenv.user.schema.json
version: 1

shell:
  prompt_prefix: false
  keybindings:
    reload: []
    toggle_pause: []
    list_watched_files: []
    toggle_error: []

tui:
  statusline:
    enabled: false