when:
  - event: ["pull_request", "push", "manual"]
    branch: ["main"]

engine: "nixery"

dependencies:
  nixpkgs:
    - coreutils
    - nix-fast-build

environment:
  NIX_CONFIG: "sandbox = false"

steps:
  - name: "Emacs"
    command: |
      nix-fast-build \
        --skip-cached \
        --no-nom \
        --flake '.#checks.x86_64-linux.doom-emacs'
