when:
  - event: ["pull_request", "push", "manual"]
    branch: ["main"]

engine: "nixery"

dependencies:
  nixpkgs:
    - coreutils

steps:
  - name: "Emacs"
    command: nix run github:Mic92/nix-fast-build -- \
      --skip-cached \
      --no-nom \
      --flake '.#checks.x86_64-linux.doom-emacs'
