#!/usr/bin/env bash
# Interactive cd to repo in ~/Code

PROJECTS_DIR=${PROJECTS_DIR:-~/Code}

# Test
project_dirs() {
  find "$PROJECTS_DIR" -maxdepth 1 -type d -not -path "$PROJECTS_DIR" | sort | xargs --max-lines=1 basename
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  query=${1:-''}
  new_dir=$(project_dirs | fzf-tmux --query "$1" --preview "if [ -f \"${PROJECTS_DIR}\"/{}/README.md ]; then glow \"${PROJECTS_DIR}\"/{}/README.md --style=dark; else ls \"${PROJECTS_DIR}\"/{}; fi")
  if [[ -n $new_dir ]]; then
    cd $PROJECTS_DIR/$new_dir
  fi
fi
