name: "Build Configurations"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: tiborpilz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#homeConfigurations.tiborpilz.activationPackage
    - run: nix build .#darwinConfigurations.bigmac.activation-package
