name: "Build Configurations"
on:
  pull_request:
  push:
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: tiborpilz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#homeConfigurations.tibor.activationPackage
    - run: nix build .#nixosConfigurations.edge.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.homeserver.config.system.build.toplevel
    - run: nix build .#nixosConfigurations.thinkyMcThinkpad.config.system.build.toplevel
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: tiborpilz
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build '.#homeConfigurations."tibor.pilz".activationPackage'
    - run: nix build '.#darwinConfigurations.bigmac.system'
